'''
Panda has Two datastructure
1. Series    1 - dimenssion
2. DataFrame 2 - dimenssion

PanelData --Pandas
Panda hetreogenous data structure

'''

In [62]:
import pandas as pd 
import numpy as np
s1=pd.Series([1,2,3,4,5,6,'abay',11.22])
s1

0        1
1        2
2        3
3        4
4        5
5        6
6     abay
7    11.22
dtype: object

In [33]:
print(s1.index)
print(s1.shape)
print(s1.size)
print(s1.values)
print(s1[3])
print(s1[2:7])

RangeIndex(start=0, stop=8, step=1)
(8,)
8
[1 2 3 4 5 6 'abay' 11.22]
4
2       3
3       4
4       5
5       6
6    abay
dtype: object

In [35]:
s2=pd.Series([11,22,33,44,55,66,77,88])
s2 *2

0     22
1     44
2     66
3     88
4    110
5    132
6    154
7    176
dtype: int64

In [37]:
s2<40

0     True
1     True
2     True
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [39]:
s2[s2<40] # filtering

0    11
1    22
2    33
dtype: int64

In [54]:
s2[(s2<50) & (s2>2)]

0    11
1    22
2    33
3    44
dtype: int64

In [64]:
# series from dictionary
dict={'Name':'Mario','Age':55}
s3=pd.Series(dict)
print(s3)

dict2={'Name':['tom','karan','mary'] , 'Mark':[66,77,88]}
s4=pd.Series(dict2)
print(s4)

Name    Mario
Age        55
dtype: object
Name    [tom, karan, mary]
Mark          [66, 77, 88]
dtype: object

In [70]:
dict3={'Name':['Amar','Akbar','Antony'], 'Mark':[77,88,99],'Age':[34,43,45]}
df1=pd.DataFrame(dict3)
df1

     Name  Mark  Age
0    Amar    77   34
1   Akbar    88   43
2  Antony    99   45

In [72]:

df1.Name

0      Amar
1     Akbar
2    Antony
Name: Name, dtype: object

In [78]:
df1[['Age','Mark','Name']]

   Age  Mark    Name
0   34    77    Amar
1   43    88   Akbar
2   45    99  Antony

In [82]:
df1[0:3]

     Name  Mark  Age
0    Amar    77   34
1   Akbar    88   43
2  Antony    99   45

In [86]:
df1['Dummy']=['q','s','d']
df1

     Name  Mark  Age Dummy
0    Amar    77   34     q
1   Akbar    88   43     s
2  Antony    99   45     d

acess row
'''
loc : locate by label , object
loc1: locate by index , only integer

'''

In [96]:
df1.loc[2]['Age']

45

In [104]:
df1.iloc[1]

Name     Akbar
Mark        88
Age         43
Dummy        s
Name: 1, dtype: object

In [108]:
df2=df1.copy()
df2.index=['a','b','c']
df2

     Name  Mark  Age Dummy
a    Amar    77   34     q
b   Akbar    88   43     s
c  Antony    99   45     d

In [112]:
df2.loc['a']

Name     Amar
Mark       77
Age        34
Dummy       q
Name: a, dtype: object

In [116]:
df2.loc['b','Mark']=75
df2

     Name  Mark  Age Dummy
a    Amar    77   34     q
b   Akbar    75   43     s
c  Antony    99   45     d

In [124]:
df2.loc['a':'b','Name':'Age']

    Name  Mark  Age
a   Amar    77   34
b  Akbar    75   43

In [138]:
df2.loc['b':'c','Dummy']=22

In [142]:
df2.loc['a':'b','Dummy']=[14,15]

In [144]:
df2

     Name  Mark  Age Dummy
a    Amar    77   34    14
b   Akbar    75   43    15
c  Antony    99   45    22

In [ ]:
df2.insert(4,'D1',89)

In [150]:
df2

     Name  Mark  Age Dummy  D1
a    Amar    77   34    14  89
b   Akbar    75   43    15  89
c  Antony    99   45    22  89

In [154]:
df2.loc['d']=['Mathew',85,25,21,65]

In [156]:
df2

     Name  Mark  Age Dummy  D1
a    Amar    77   34    14  89
b   Akbar    75   43    15  89
c  Antony    99   45    22  89
d  Mathew    85   25    21  65

In [158]:
df2[df2.Age>40]

     Name  Mark  Age Dummy  D1
b   Akbar    75   43    15  89
c  Antony    99   45    22  89

In [160]:
df2.insert(0,'Roll No',[1,2,3,4])

In [162]:
df2

   Roll No    Name  Mark  Age Dummy  D1
a        1    Amar    77   34    14  89
b        2   Akbar    75   43    15  89
c        3  Antony    99   45    22  89
d        4  Mathew    85   25    21  65

In [202]:
fairdealdata=pd.read_csv('Class Note/dataset/FairDealCustomerData.csv',header=None)
fairdealdata

              0                      1  2
0        Braund       Mr. Owen Harris   1
1     Heikkinen           Miss. Laina   0
2         Allen     Mr. William Henry   0
3         Moran             Mr. James   0
4      McCarthy         Mr. Timothy J   0
..          ...                    ... ..
527    Banfield   Mr. Frederick James   0
528    Sutehall          Mr. Henry Jr   0
529    Montvila           Rev. Juozas   0
530        Behr       Mr. Karl Howell   0
531      Dooley           Mr. Patrick   0

[532 rows x 3 columns]

In [204]:
fairdealdata.columns

Index([0, 1, 2], dtype='int64')

In [206]:
fairdealdata.columns=['Name','FullName','Status']

In [198]:
#fairdealdata.rename(columns = {' Braund':'Brand'},inplace=True)

In [208]:
fairdealdata

           Name               FullName  Status
0        Braund       Mr. Owen Harris        1
1     Heikkinen           Miss. Laina        0
2         Allen     Mr. William Henry        0
3         Moran             Mr. James        0
4      McCarthy         Mr. Timothy J        0
..          ...                    ...     ...
527    Banfield   Mr. Frederick James        0
528    Sutehall          Mr. Henry Jr        0
529    Montvila           Rev. Juozas        0
530        Behr       Mr. Karl Howell        0
531      Dooley           Mr. Patrick        0

[532 rows x 3 columns]

In [210]:
fairdealdata.to_json('fairdeal.json')

In [212]:
df3=pd.read_json('fairdeal.json')

In [214]:
df3

           Name               FullName  Status
0        Braund       Mr. Owen Harris        1
1     Heikkinen           Miss. Laina        0
2         Allen     Mr. William Henry        0
3         Moran             Mr. James        0
4      McCarthy         Mr. Timothy J        0
..          ...                    ...     ...
527    Banfield   Mr. Frederick James        0
528    Sutehall          Mr. Henry Jr        0
529    Montvila           Rev. Juozas        0
530        Behr       Mr. Karl Howell        0
531      Dooley           Mr. Patrick        0

[532 rows x 3 columns]

In [218]:
df4=pd.read_excel('Class Note/dataset/test.xlsx')

In [220]:
df4

  StockName  Price
0    Amazon    100
1    Google    200
2     Apple    300

In [224]:
fairdealdata.drop(3,inplace=True)

In [228]:
fairdealdata.sort_index()

<bound method DataFrame.sort_index of            Name               FullName  Status
0        Braund       Mr. Owen Harris        1
1     Heikkinen           Miss. Laina        0
2         Allen     Mr. William Henry        0
4      McCarthy         Mr. Timothy J        0
5       Bonnell       Miss. Elizabeth        0
..          ...                    ...     ...
527    Banfield   Mr. Frederick James        0
528    Sutehall          Mr. Henry Jr        0
529    Montvila           Rev. Juozas        0
530        Behr       Mr. Karl Howell        0
531      Dooley           Mr. Patrick        0

[531 rows x 3 columns]>

In [230]:
fairdealdata.reset_index()

     index        Name               FullName  Status
0        0      Braund       Mr. Owen Harris        1
1        1   Heikkinen           Miss. Laina        0
2        2       Allen     Mr. William Henry        0
3        4    McCarthy         Mr. Timothy J        0
4        5     Bonnell       Miss. Elizabeth        0
..     ...         ...                    ...     ...
526    527    Banfield   Mr. Frederick James        0
527    528    Sutehall          Mr. Henry Jr        0
528    529    Montvila           Rev. Juozas        0
529    530        Behr       Mr. Karl Howell        0
530    531      Dooley           Mr. Patrick        0

[531 rows x 4 columns]

In [240]:
fairdealdata.drop('Status',axis=1,inplace=True)

In [242]:
fairdealdata

           Name               FullName
0        Braund       Mr. Owen Harris
1     Heikkinen           Miss. Laina
2         Allen     Mr. William Henry
4      McCarthy         Mr. Timothy J
5       Bonnell       Miss. Elizabeth
..          ...                    ...
527    Banfield   Mr. Frederick James
528    Sutehall          Mr. Henry Jr
529    Montvila           Rev. Juozas
530        Behr       Mr. Karl Howell
531      Dooley           Mr. Patrick

[531 rows x 2 columns]

In [ ]:
fairdealdata[fairdealdata.Name.duplicated()]

In [256]:
fairdealdata.Name=fairdealdata.Name.str.strip()

In [296]:
fairdealdata[fairdealdata.Name=='Williams']

        Name              FullName
7   Williams   Mr. Charles Eugene
86  Williams    Mr. Charles Eugene

In [282]:

fairdealdata.loc[86,'FullName']='Mr. Charles Eugene'

In [308]:
fairdealdata.drop_duplicates(inplace=True)

In [306]:
fairdealdata.loc[86]=fairdealdata.loc[7]

In [310]:
fairdealdata[fairdealdata.Name=='Williams']

       Name              FullName
7  Williams   Mr. Charles Eugene

In [12]:
citytemp=pd.read_csv('Class Note/dataset/CityTemps1.csv')
citytemp

      Year  Month  Moscow  Melbourne  San Francisco
0   2014.0    1.0    -8.6       22.0           12.8
1   2014.0    2.0     NaN       21.5           12.7
2   2014.0    3.0     2.8       19.5            NaN
3   2014.0    4.0     7.0        NaN           15.7
4   2014.0    5.0    16.0       13.9           17.5
5      NaN    NaN     NaN        NaN            NaN
6   2014.0    7.0    21.1        9.9           19.4
7   2014.0    8.0    19.2        NaN           19.5
8   2014.0    9.0     NaN       12.8           20.2
9   2014.0   10.0     3.7       15.6           20.4
10  2014.0   11.0     NaN       17.3            NaN
11  2014.0   12.0    -3.9       18.9           13.8
12  2015.0    1.0    -4.4       20.4           12.2
13  2015.0    2.0    -2.2       21.8           14.8
14  2015.0    3.0     2.0       17.4           15.7
15  2015.0    4.0     6.1       14.1           14.8
16  2015.0    5.0    14.2       12.6           14.7
17  2015.0    6.0    17.9        9.8           17.1
18  2015.0    7.0    18.3        NaN           19.3
19  2015.0    8.0    17.6        9.8           20.0
20  2015.0    9.0     NaN       12.1           19.5
21  2015.0   10.0     4.4       18.1           18.7
22  2015.0   11.0     0.8       17.4            NaN
23  2015.0   12.0     0.2       21.3           10.3

In [14]:
citytemp.info()
citytemp[citytemp.Year.isnull()]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           23 non-null     float64
 1   Month          23 non-null     float64
 2   Moscow         19 non-null     float64
 3   Melbourne      20 non-null     float64
 4   San Francisco  20 non-null     float64
dtypes: float64(5)
memory usage: 1.1 KB

   Year  Month  Moscow  Melbourne  San Francisco
5   NaN    NaN     NaN        NaN            NaN

In [332]:
citytemp[citytemp.Moscow.isnull()]

Empty DataFrame
Columns: [Year, Month, Moscow, Melbourne, San Francisco]
Index: []

In [324]:
citytemp.Moscow.mean()

6.957894736842104

In [32]:
citytemp.Moscow.fillna(citytemp.Moscow.mean(),inplace=True)

In [34]:
citytemp.loc[5:20]

      Year  Month     Moscow  Melbourne  San Francisco
5      NaN    NaN   6.957895        NaN            NaN
6   2014.0    7.0  21.100000        9.9           19.4
7   2014.0    8.0  19.200000        NaN           19.5
8   2014.0    9.0   6.957895       12.8           20.2
9   2014.0   10.0   3.700000       15.6           20.4
10  2014.0   11.0   6.957895       17.3            NaN
11  2014.0   12.0  -3.900000       18.9           13.8
12  2015.0    1.0  -4.400000       20.4           12.2
13  2015.0    2.0  -2.200000       21.8           14.8
14  2015.0    3.0   2.000000       17.4           15.7
15  2015.0    4.0   6.100000       14.1           14.8
16  2015.0    5.0  14.200000       12.6           14.7
17  2015.0    6.0  17.900000        9.8           17.1
18  2015.0    7.0  18.300000        NaN           19.3
19  2015.0    8.0  17.600000        9.8           20.0
20  2015.0    9.0   6.957895       12.1           19.5

In [ ]:
citytemp.Moscow.sort_values()

In [28]:
temporig=citytemp.head(5)

In [36]:
temporig

     Year  Month     Moscow  Melbourne  San Francisco
0  2014.0    1.0  -8.600000       22.0           12.8
1  2014.0    2.0   6.957895       21.5           12.7
2  2014.0    3.0   2.800000       19.5            NaN
3  2014.0    4.0   7.000000        NaN           15.7
4  2014.0    5.0  16.000000       13.9           17.5

In [ ]:
temporig.loc[2,'Year']=2016
temporig.loc[3,'Year']=2017
temporig.loc[4,'Year']=2018

In [52]:
temporig

     Year  Month     Moscow  Melbourne  San Francisco
0  2014.0    1.0  -8.600000       22.0           12.8
1  2015.0    2.0   6.957895       21.5           12.7
2  2016.0    3.0   2.800000       19.5            NaN
3  2017.0    4.0   7.000000        NaN           15.7
4  2018.0    5.0  16.000000       13.9           17.5

temporig.Melbourne.fillna(100,inplace=True)

In [75]:
temp=citytemp.head(5)

In [77]:
temp

     Year  Month     Moscow  Melbourne  San Francisco
0  2014.0    1.0  -8.600000       22.0           12.8
1  2015.0    2.0   6.957895       21.5           12.7
2  2016.0    3.0   2.800000       19.5            NaN
3  2017.0    4.0   7.000000        NaN           15.7
4  2018.0    5.0  16.000000       13.9           17.5

In [85]:
temp.replace(np.nan,100,inplace=True)

C:\Users\ABHAY\AppData\Local\Temp\ipykernel_15588\183065255.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp.replace(np.nan,100,inplace=True)

In [87]:
temp

     Year  Month     Moscow  Melbourne  San Francisco
0  2014.0    1.0  -8.600000       22.0           12.8
1  2015.0    2.0   6.957895       21.5           12.7
2  2016.0    3.0   2.800000       19.5          100.0
3  2017.0    4.0   7.000000      100.0           15.7
4  2018.0    5.0  16.000000       13.9           17.5

In [89]:
temp1=temp[['Year','Month','Moscow']]

In [91]:
temp1

     Year  Month     Moscow
0  2014.0    1.0  -8.600000
1  2015.0    2.0   6.957895
2  2016.0    3.0   2.800000
3  2017.0    4.0   7.000000
4  2018.0    5.0  16.000000

In [93]:
temp2=temp[['Year','Melbourne','San Francisco']]

In [95]:
temp2

     Year  Melbourne  San Francisco
0  2014.0       22.0           12.8
1  2015.0       21.5           12.7
2  2016.0       19.5          100.0
3  2017.0      100.0           15.7
4  2018.0       13.9           17.5

In [ ]:
temp2.loc[4,'Year']=2024

In [103]:
temp2

     Year  Melbourne  San Francisco
0  2014.0       22.0           12.8
1  2020.0       21.5           12.7
2  2016.0       19.5          100.0
3  2017.0      100.0           15.7
4  2024.0       13.9           17.5

In [111]:
temp2.merge(temp1,on='Year',how='outer')

     Year  Melbourne  San Francisco  Month     Moscow
0  2014.0       22.0           12.8    1.0  -8.600000
1  2015.0        NaN            NaN    2.0   6.957895
2  2016.0       19.5          100.0    3.0   2.800000
3  2017.0      100.0           15.7    4.0   7.000000
4  2018.0        NaN            NaN    5.0  16.000000
5  2020.0       21.5           12.7    NaN        NaN
6  2024.0       13.9           17.5    NaN        NaN

In [115]:
# group by
bank=pd.read_csv('Class Note/dataset/bank-data.csv')

In [117]:
bank

     age            job  marital    y
0     20        student   single  yes
1     32     management   single  yes
2     49     technician  married  yes
3     32    blue-collar  married  yes
4     33     management  married  yes
..   ...            ...      ...  ...
442   26     technician   single  yes
443   60  self-employed  married  yes
444   42    blue-collar   single  yes
445   32         admin.   single  yes
446   46    blue-collar  married  yes

[447 rows x 4 columns]

In [119]:
bank.groupby('job')

In [121]:
for i in bank.groupby('job'):
    print(i)

('admin.',      age     job   marital    y
5     61  admin.   married  yes
9     27  admin.  divorced  yes
18    55  admin.   married  yes
25    34  admin.   married  yes
32    25  admin.    single  yes
39    48  admin.  divorced  yes
43    54  admin.   married  yes
49    61  admin.   married  yes
50    53  admin.   married  yes
51    46  admin.   married  yes
57    47  admin.    single  yes
85    41  admin.    single  yes
87    26  admin.    single  yes
100   37  admin.   married  yes
104   45  admin.   married  yes
110   38  admin.   married  yes
116   44  admin.   married  yes
128   46  admin.  divorced  yes
133   45  admin.   married  yes
135   27  admin.   married  yes
138   46  admin.   married  yes
153   47  admin.  divorced  yes
154   42  admin.  divorced  yes
167   43  admin.   married  yes
172   46  admin.   married  yes
175   53  admin.    single  yes
176   40  admin.    single  yes
178   49  admin.   married  yes
190   34  admin.   married  yes
204   41  admin.  divorced  yes
214   31  admin.    single  yes
221   41  admin.   married  yes
239   35  admin.    single  yes
253   35  admin.  divorced  yes
259   34  admin.  divorced  yes
270   45  admin.  divorced  yes
303   56  admin.   married  yes
304   46  admin.   married  yes
307   60  admin.   married  yes
313   34  admin.   married  yes
320   32  admin.    single  yes
323   28  admin.    single  yes
334   33  admin.   married  yes
338   33  admin.   married  yes
339   53  admin.   married  yes
340   27  admin.   married  yes
356   29  admin.    single  yes
362   30  admin.    single  yes
370   42  admin.    single  yes
377   33  admin.   married  yes
381   39  admin.   married  yes
391   47  admin.   married  yes
396   34  admin.    single  yes
400   52  admin.    single  yes
429   34  admin.  divorced  yes
430   49  admin.   married  yes
434   45  admin.  divorced  yes
445   32  admin.    single  yes)
('blue-collar',      age          job   marital    y
3     32  blue-collar   married  yes
6     45  blue-collar  divorced  yes
21    29  blue-collar    single  yes
23    29  blue-collar    single  yes
24    24  blue-collar    single  yes
..   ...          ...       ...  ...
432   29  blue-collar    single  yes
435   32  blue-collar    single  yes
438   49  blue-collar    single  yes
444   42  blue-collar    single  yes
446   46  blue-collar   married  yes

[69 rows x 4 columns])
('entrepreneur',      age           job   marital    y
27    49  entrepreneur  divorced  yes
29    38  entrepreneur   married  yes
31    49  entrepreneur   married  yes
33    35  entrepreneur   married  yes
35    35  entrepreneur    single  yes
107   63  entrepreneur   married  yes
206   37  entrepreneur  divorced  yes
229   43  entrepreneur   married  yes
230   23  entrepreneur    single  yes
283   38  entrepreneur   married  yes
306   38  entrepreneur    single  yes
360   36  entrepreneur   married  yes
401   53  entrepreneur   married  yes
409   55  entrepreneur  divorced  yes
433   41  entrepreneur   married  yes)
('housemaid',      age        job   marital    y
83    55  housemaid  divorced  yes
86    31  housemaid    single  yes
143   56  housemaid  divorced  yes
177   49  housemaid   married  yes
197   48  housemaid   married  yes
222   35  housemaid   married  yes
223   47  housemaid    single  yes
255   53  housemaid   married  yes
291   51  housemaid  divorced  yes
295   34  housemaid   married  yes
363   80  housemaid   married  yes
380   29  housemaid    single  yes
398   38  housemaid  divorced  yes
424   34  housemaid   married  yes)
('management',      age         job  marital    y
1     32  management   single  yes
4     33  management  married  yes
8     37  management  married  yes
11    37  management  married  yes
17    52  management  married  yes
..   ...         ...      ...  ...
436   45  management   single  yes
437   40  management  married  yes
439   29  management   single  yes
440   38  management   single  yes
441   38  management  married  yes

[131 rows x 4 columns])
('self-employed',      age            job   marital    y
16    34  self-employed    single  yes
47    34  self-employed    single  yes
62    41  self-employed   married  yes
65    58  self-employed  divorced  yes
68    46  self-employed   married  yes
73    35  self-employed  divorced  yes
96    58  self-employed   married  yes
99    59  self-employed   married  yes
119   28  self-employed    single  yes
161   39  self-employed    single  yes
187   51  self-employed   married  yes
308   51  self-employed   married  yes
331   28  self-employed    single  yes
342   33  self-employed    single  yes
343   39  self-employed   married  yes
352   61  self-employed  divorced  yes
395   44  self-employed    single  yes
407   50  self-employed  divorced  yes
417   62  self-employed  divorced  yes
443   60  self-employed   married  yes)
('services',      age       job   marital    y
10    52  services   married  yes
12    27  services    single  yes
36    32  services   married  yes
61    32  services    single  yes
71    28  services    single  yes
82    39  services    single  yes
90    28  services    single  yes
106   34  services   married  yes
122   34  services   married  yes
141   38  services    single  yes
146   45  services    single  yes
149   53  services  divorced  yes
164   47  services    single  yes
198   30  services    single  yes
203   42  services  divorced  yes
226   33  services   married  yes
227   40  services   married  yes
236   24  services   married  yes
241   27  services    single  yes
244   43  services    single  yes
245   35  services   married  yes
261   49  services   married  yes
286   49  services   married  yes
315   33  services   married  yes
318   47  services   married  yes
332   60  services   married  yes
341   46  services   married  yes
347   58  services  divorced  yes
350   33  services  divorced  yes
357   29  services  divorced  yes
358   26  services    single  yes
359   32  services   married  yes
365   32  services    single  yes
368   27  services   married  yes
378   53  services  divorced  yes
386   31  services  divorced  yes
411   32  services    single  yes
418   39  services  divorced  yes)
('student',      age      job  marital    y
0     20  student   single  yes
13    21  student   single  yes
14    25  student   single  yes
53    19  student   single  yes
89    27  student   single  yes
157   28  student   single  yes
170   25  student   single  yes
195   28  student   single  yes
200   22  student   single  yes
202   27  student   single  yes
233   24  student   single  yes
252   22  student   single  yes
267   27  student   single  yes
281   19  student   single  yes
301   22  student   single  yes
345   28  student   single  yes
383   26  student   single  yes
405   25  student   single  yes
426   25  student  married  yes)
('technician',      age         job  marital    y
2     49  technician  married  yes
7     34  technician  married  yes
15    25  technician   single  yes
20    35  technician   single  yes
40    60  technician   single  yes
..   ...         ...      ...  ...
419   38  technician   single  yes
421   33  technician   single  yes
422   36  technician   single  yes
425   59  technician  married  yes
442   26  technician   single  yes

[83 rows x 4 columns])

In [123]:
bank_group=bank.groupby('job')
bank_group.groups

{'admin.': [5, 9, 18, 25, 32, 39, 43, 49, 50, 51, 57, 85, 87, 100, 104, 110, 116, 128, 133, 135, 138, 153, 154, 167, 172, 175, 176, 178, 190, 204, 214, 221, 239, 253, 259, 270, 303, 304, 307, 313, 320, 323, 334, 338, 339, 340, 356, 362, 370, 377, 381, 391, 396, 400, 429, 430, 434, 445], 'blue-collar': [3, 6, 21, 23, 24, 26, 28, 30, 42, 48, 54, 56, 59, 78, 81, 91, 93, 97, 102, 105, 109, 111, 125, 140, 148, 162, 163, 171, 182, 189, 191, 211, 217, 228, 235, 240, 246, 264, 273, 276, 278, 287, 297, 311, 317, 327, 330, 333, 336, 353, 361, 369, 387, 397, 399, 402, 403, 406, 410, 412, 414, 416, 420, 431, 432, 435, 438, 444, 446], 'entrepreneur': [27, 29, 31, 33, 35, 107, 206, 229, 230, 283, 306, 360, 401, 409, 433], 'housemaid': [83, 86, 143, 177, 197, 222, 223, 255, 291, 295, 363, 380, 398, 424], 'management': [1, 4, 8, 11, 17, 19, 22, 34, 37, 38, 41, 44, 45, 58, 64, 66, 67, 69, 72, 74, 76, 77, 79, 80, 84, 92, 95, 98, 108, 115, 118, 120, 123, 124, 127, 129, 130, 131, 132, 134, 137, 142, 145, 147, 156, 158, 159, 160, 168, 169, 173, 179, 183, 184, 186, 188, 193, 194, 196, 199, 207, 208, 210, 212, 218, 219, 220, 224, 225, 231, 232, 237, 238, 242, 247, 249, 250, 254, 257, 258, 262, 263, 265, 268, 269, 271, 272, 279, 280, 285, 288, 292, 294, 299, 300, 302, 310, 314, 319, 321, ...], 'self-employed': [16, 47, 62, 65, 68, 73, 96, 99, 119, 161, 187, 308, 331, 342, 343, 352, 395, 407, 417, 443], 'services': [10, 12, 36, 61, 71, 82, 90, 106, 122, 141, 146, 149, 164, 198, 203, 226, 227, 236, 241, 244, 245, 261, 286, 315, 318, 332, 341, 347, 350, 357, 358, 359, 365, 368, 378, 386, 411, 418], 'student': [0, 13, 14, 53, 89, 157, 170, 195, 200, 202, 233, 252, 267, 281, 301, 345, 383, 405, 426], 'technician': [2, 7, 15, 20, 40, 46, 52, 55, 60, 63, 70, 75, 88, 94, 101, 103, 112, 113, 114, 117, 121, 126, 136, 139, 144, 150, 151, 152, 155, 165, 166, 174, 180, 181, 185, 192, 201, 205, 209, 213, 215, 216, 234, 243, 248, 251, 256, 260, 266, 274, 275, 277, 282, 284, 289, 290, 293, 296, 298, 305, 309, 312, 316, 322, 328, 344, 349, 351, 366, 367, 372, 379, 382, 384, 389, 390, 408, 415, 419, 421, 422, 425, 442]}

In [129]:
bank[bank.job=='student']

     age      job  marital    y
0     20  student   single  yes
13    21  student   single  yes
14    25  student   single  yes
53    19  student   single  yes
89    27  student   single  yes
157   28  student   single  yes
170   25  student   single  yes
195   28  student   single  yes
200   22  student   single  yes
202   27  student   single  yes
233   24  student   single  yes
252   22  student   single  yes
267   27  student   single  yes
281   19  student   single  yes
301   22  student   single  yes
345   28  student   single  yes
383   26  student   single  yes
405   25  student   single  yes
426   25  student  married  yes

In [131]:
bank_group.count()

               age  marital    y
job
admin.          58       58   58
blue-collar     69       69   69
entrepreneur    15       15   15
housemaid       14       14   14
management     131      131  131
self-employed   20       20   20
services        38       38   38
student         19       19   19
technician      83       83   83